modLoader="javafml"
loaderVersion="[35,)"
license="GPL v3"

[[mods]]
    modId="vivecraftforgeextensions"
    version="1.3.3-with-API-0.1.0"
    displayName="Vivecraft Forge Extensions with API"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/vivecraft-forge-extensions"
    logoFile="logo.png"
    authors="Mostly Techjar, with a bit of hammy3502"
    description="Forge companion mod for Vivecraft which handles packets and modifies base code for VR players while exposing an API for mod authors to take advantage of."

[[dependencies.vivecraftforgeextensions]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vivecraftforgeextensions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
